### PR TITLE
Update: Rails 5.1, Ruby 2.5, Ubuntu 16.04

### PR DESCRIPTION
**Pull request by mike-yesware**
The Ruby and Rails updates tested fine, but maybe require another quick pass at the docs. I'll certainly want to update the docs to recommend latest Vagrant and VirtualBox, as that's where most of my testing occurred.

The Ubuntu issue root case seen at the last meetup, is related to Vagrant's automatic replacement of SSH keys for the `vagrant` user, not the `ubuntu` user. By standardizing on the `vagrant` user this box has tested well for a variety of users. This didn't work when Xenial was first release, but Ubuntu has since made upstream changes.

### CODE REVIEW

**Comment by decklin** [comment]
Looks good, thank you - can we just fix the grammar in this comment

`# We need to fix a on thing`

i think that was meant to be updated to "fix one thing". Thanks!

**Comment by decklin** [comment]
Yeah, the user rename from `ubuntu` to `vagrant` is not a thing when I attempt to build this. After `vagrant up` times out on auth and the VM is still running, this fails:

`ssh -p 2222 -i .vagrant/machines/default/virtualbox/private_key -v vagrant@localhost`

but `ubuntu@` works. Could this be something left over on my dev machine somehow from upgrading from previous versions of VirtualBox and Vagrant?

(I mean, we're starting with the upstream, pristine image still, yes, so there *is* an `ubuntu` user still, right? I'm not wildly off here?)

**Comment by edwardloveall** [comment]
The box from your dropbox @mike-yesware works flawlessly for me, first try with the new Vagrant and Virtualbox

**Comment by decklin** [comment]
@edwardloveall thanks, can you try the build at http://downloads.railsbridge.org/railsbridgevm-2018-03-rc1.box ? should be exactly the same content (built after merging).

**Comment by edwardloveall** [comment]
Yup, looks good to me!

**Comment by mike-yesware** [comment]
Tested good for me as well. I destroyed my previous `railsbridge` VM and removed the associated box first. Also tested port forwarding for `3000` and that worked too.

**Pull request merged**
